### ISSUE TITLE
Diff being rearranged using diffWords/diffChars

### ISSUE THREAD

**Issue by Nibor808** [kpdecker/jsdiff#125]
this is the difference:
04/28/2016 Notice-Case Review Re Judgment
`<p><b>04/28/2016</b> Notice-Case Review Re Judgment</p>`

this is the output:
28/2016 Notice-Case Review Re Judgment04/

Not sure what's causing the rearranging

**Comment by ExplodingCabbage** [comment]
I don't understand this issue. What two texts are being diffed, with what diffing algo? How can "the output" of running a diff simply be another text rather than a list of change objects?

I tried diffing the two lines given in this issue against each other in a couple of ways but didn't see the `04/` jumping to the end in the list of change objects returned:

```
> diff.diffWords("04/28/2016 Notice-Case Review Re Judgment", "<p><b>04/28/2016</b> Notice-Case Review Re Judgment</p>")
[
  { count: 5, added: true, removed: undefined, value: '<p><b>' },
  { count: 5, value: '04/28/2016' },
  { count: 3, added: true, removed: undefined, value: '</b>' },
  { count: 10, value: ' Notice-Case Review Re Judgment' },
  { count: 3, added: true, removed: undefined, value: '</p>' }
]
> diff.diffChars("04/28/2016 Notice-Case Review Re Judgment", "<p><b>04/28/2016</b> Notice-Case Review Re Judgment</p>")
[
  { count: 6, added: true, removed: undefined, value: '<p><b>' },
  { count: 10, value: '04/28/2016' },
  { count: 4, added: true, removed: undefined, value: '</b>' },
  { count: 31, value: ' Notice-Case Review Re Judgment' },
  { count: 4, added: true, removed: undefined, value: '</p>' }
]
```

Since I can't make sense of the report, I'm gonna close this; @Nibor808 if you can provide a clearer explanation then I'd be happy to reopen and take another look.

**Comment by Nibor808** [comment]
No idea. This was almost 8 years ago :(
