### ISSUE TITLE
diffChars wildcard/mapping

### ISSUE THREAD

**Issue by thomasdebruin** [kpdecker/jsdiff#127]
Is there any option to use a wildcard or mapping for certain characeters when using diffChars? Lets say I compare 2 pieces but it shouldn't matter whetere someone types: {.||,},{ij||y} etc.
Probably beyond the scope of this plugin.

**Comment by thomasdebruin** [comment]
Okay, I solved this by replacing the ij (similar on some writing and pronouncement in Dutch language) with a placeholder character (special char like #) then made my own extend of the base js, in that extend the 'equals' function then treats the # like an ij and returns true if it's equal to y.

Maybe it's not the most sophistacated solution but it works.

**Comment by ExplodingCabbage** [comment]
Yeah, some mixture of replacing characters or character sequences with placeholders (which could be `Symbol` objects if you're willing to use `diffArrays` instead of `diffChars`) and/or overriding `.equals` seems like the right solution here!

I've made a ticket for creating some docs about that: https://github.com/kpdecker/jsdiff/issues/432
