### ISSUE TITLE
context argument doesn't work in some methods

### ISSUE THREAD

**Issue by liusiomn** [kpdecker/jsdiff#145]
`    function diffChars(oldStr:string, newStr:string):IDiffResult[];

```
function diffWords(oldStr:string, newStr:string):IDiffResult[];

function diffWordsWithSpace(oldStr:string, newStr:string):IDiffResult[];

function diffJson(oldObj: Object, newObj: Object): IDiffResult[];

function diffLines(oldStr:string, newStr:string):IDiffResult[];

function diffCss(oldStr:string, newStr:string):IDiffResult[];

function createPatch(fileName: string, oldStr: string, newStr: string, oldHeader: string, newHeader: string, options?: {context: number}): string;`
```

some methods seem don't have context argument. However, those method should have according to your API readme.

**Comment by ExplodingCabbage** [comment]
Looks like this report is about the TypeScript type definitions contained in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), which aren't part of jsdiff nor maintained by its maintainers (though perhaps jsdiff *should* have its own type definitions!). Also looks like this has at least partly fixed by now (perhaps completely - I didn't check).

**Comment by ExplodingCabbage** [comment]
Separate issue for making type definitions part of jsdiff: https://github.com/kpdecker/jsdiff/issues/303
