### ISSUE TITLE
Allow option to limit number of hunks.

### ISSUE THREAD

**Issue by dead-claudia** [kpdecker/jsdiff#164]
In the case of printing to console (e.g. in Mocha, which depends on this), a flood of text from a large diff can be hard to read, and when printing diffs for mock DOM nodes, that makes things even *harder*, with the object diff increasing exponentially. IMHO, that's partially a Mocha issue for trying to re-implement half of `JSON.stringify`, but it'd also be exceptionally nice to have a backoff option for `diff.createPatch` and friends, in these pathological cases.

**Comment by ExplodingCabbage** [comment]
I'm not 100% sure I understand what's being asked for here, but if I understand right then I think what's being requested is basically impossible, at least as long as jsdiff remains based on the Myers diff algorithm. If I understand right then the request is for a way to make jsdiff abort after a certain number of changes and return just the first n lines of the diff. But until the diff is complete, the algorithm doesn't yet *know* what the first n lines of the diff will be, because it's exploring multiple possible paths through the edit graph (corresponding to different possible starts to the diff) simultaneously and won't know which is optimal until one of them reaches the end. For that reason I don't think it makes sense to attempt to implement something like this.

**Comment by dead-claudia** [comment]
Fair enough, and it's been so long I forgot I filed this and only remembered experiencing the issue with Mocha's diffs. 😂
