### ISSUE TITLE
Feature request: createPatch using diffwords / diffchars?

### ISSUE THREAD

**Issue by Ch0ronomato** [kpdecker/jsdiff#184]
Is there a way you could either implement the above functionality, or give me an explanation of why it isn't there so maybe I can implement it? Essentially I just want to createPatch (or structurePatch since the other patch methods rely on it) and use diffchars or diffwords instead of difflines. If I had to guess, difflines is probably the standard method for doing patches, but anyway.

Any guidance you could give on implementing this?

**Comment by ted537** [comment]
The patch operations (apply/create/merge) appear to all assume that newlines are the delimiter. Modifying this would mean not only switching out the delimiter, but modifying any code that makes these assumptions using a parameter in the options argument.

I suppose a quick and dirty solution would be converting spaces to newlines with some identifying hash or something on each, and then using the existing patch methods.

To properly handle patches for non-line based diffs, perhaps a separate module should be included that uses a data format more similar to the diff methods where delimiters are included in the tokens.

**Comment by ExplodingCabbage** [comment]
Yeah, the problem here is that the unified diff format used by `createPatch` / `updatePatch` / etc is a line-based file format that is only capable of describing the deletion and insertion of entire lines, not parts of lines. So there simply isn't any way to encode the output of `diffWords` or `diffChars` in that format, making this request impossible to implement.

(If there's a format that _would_ be appropriate for the task, I'd certainly consider a feature request to implement serialization of character or word diffs to that format.)
