### ISSUE TITLE
create option to ignore line or key (if json)

### ISSUE THREAD

**Issue by microsoftly** [kpdecker/jsdiff#195]

**Comment by ExplodingCabbage** [comment]
I think I'm against adding stuff like this to the library because there's an almost limitless set of kinda-arbitrary ways to pre-transform objects or tweak how we convert them to JSON that could in theory be useful in some particular use case. If we add this, why not an option to sort all arrays in the object, or convert numbers to strings, or convert all strings to lowercase, or treat an array of strings as equal to a string containing those same elements separated by commas, etc etc etc.

IMO all these ideas share a few common characteristics with what's asked for in this issue:
* they're easy to implement in userland with a preprocessing step
* they're kinda arbitrary and will probably only be useful to like 2% of users of diffJson or less
* I worry that adding options for them will give the misleading impression to a user that the options are *clever* in some way and that they should be leaning on the library's functionality for these kind of rules... when in reality the whole `diffJson` method is basically a crude hack (we just serialize and then diff with `diffLines`) and if we were to implement these options it'd just be with a preprocessing step that the user could've easily written themselves in userland.

Instead I think the right answer is for users of the library to just do that preprocessing step themselves - e.g. in your case I guess you'd want to deep-clone the objects you're diffing, recurse over the clones `delete`ing the keys you want to ignore, and then diff the clones.
