### ISSUE TITLE
Import statement for jsdiff

### ISSUE THREAD

**Issue by harmeetjaipur** [kpdecker/jsdiff#199]
Hi, I have been looking for a good diff checker that can deal with html inside the content and your project seems like it can deal with that. 

I feel stupid asking this but what is the import name for jsdiff for ReactJs? I tried `import JsDiff from 'diff'` but `JsDiff` stays undefined.

**Comment by harmeetjaipur** [comment]
Found the '*' solution on another post.

**Comment by devloe** [comment]
Can you post the solution here?

**Comment by Martii** [comment]
@devloe 
This is the core npmjs.com package at https://www.npmjs.com/package/diff . So `package.json` item should be, at current, `"diff": "4.0.1"`

Seems there is some current README.md issues too with using `JsDiff` *(ex. [here](https://github.com/kpdecker/jsdiff/blob/305a2b33da24c4a5cd1a547529ce06ecb00cb0a5/README.md#api) and a bunch of other places in this DOC)*... almost skipped this update with `diff`@4.0.1 since it failed in usage tests. Had to change `JsDiff` Object reference in DOM script to plain `Diff`. Cc: @kpdecker

**Comment by clouedoc** [comment]
The `*` solution if anyone is wondering. Thanks to the OP.

```
import * as Diff from "diff";
```
