### ISSUE TITLE
Change tracking

### ISSUE THREAD

**Issue by salarmehr** [kpdecker/jsdiff#203]
I appreciate developing this really handy project. 

Instead of merging I need to use jsdiff for change tracking. In the same way that it works in MS word or Google Docs.

I need to present the user a single text editor pre-filled with some paragraphs and once user start typing he sees changes real-time and in-line. 

Can you please advise how can I achieve this result please?

**Comment by ExplodingCabbage** [comment]
This sounds like something you don't need a diffing algorithm for, since you can literally just keep a history of the user's changes that you append to as they make them. Indeed you *couldn't* use a diffing algorithm for this because an optimal (i.e. number-of-edits-minimising) diff between the original and modified texts would often not match the actual edit history, and with change tracking you want to show the changes the user *actually made*, not the smallest set of edits that they could've theoretically used to transform the first text into the second.

I can imagine a feature where someone uploads a locally-modified version of a file and you use jsdiff to fake up a track changes history, but the *core* functionality of a Track Changes, described in the issue here, simply has no need for a library like jsdiff and shouldn't use it.
