### ISSUE TITLE
Rename diffJson to diffObjects

### ISSUE THREAD

**Issue by mfulton26** [kpdecker/jsdiff#220]
JSON objects are strings.

Can `diffJson` be renamed to `diffObjects` as it takes two objects, not two JSON objects.

Thanks.

**Comment by tinacious** [comment]
Thank you for making this issue. Because of this I realized to have `Diff.diffJson` reflect the expected outcome of omitting reordered properties as specified in the [docs](https://github.com/kpdecker/jsdiff/tree/da6cf291408ee6a38bb715aff32a884b98f55d80#api), I needed to run `JSON.parse` on the JSON strings beforehand. 🙏 

If renaming the method is too intense of a change, perhaps it may be better to enhance the documentation so that it is clear that a JavaScript object is required rather than a JSON string. 

Alternatively, having it `console.warn` about the inappropriate type.

This is a great library. Thanks to all the contributors for all your hard work. 🙏

**Comment by Zhouzi** [comment]
The thing is that `diffObject` would imply that it's able to detect all the differences between JavaScript objects, while it doesn't. It doesn't detect the differences between objects whose type would be `Date`, `Function`, `Promise` or anything that is not serializable to JSON.

So I think the name is great in that perspective. If it really is confusing to most users, it could perhaps be renamed to `diffJsonObject`. And at the same time, there's `diffChars` / `diffLines` for JSON strings.
