### ISSUE TITLE
Do we need to remove diffJson?

### ISSUE THREAD

**Issue by plainweaver** [kpdecker/jsdiff#255]
It seems diffJson does its job by stringifying object internally.

It would be better if there is ```diffObject``` which dives into an object tree.
Determine types in every key met with ```typeof``` then calc with already existing methods, diffArray and so on.

I'll pull request when it seems valid to you

**Comment by ExplodingCabbage** [comment]
I also find `diffJson` kinda hacky and inelegant, but since it's there, I don't want to break backwards compatibility by removing it.

I don't think I'd agree with adding the recursive tree-diving `diffObject` function you propose, either. What would it return? As far as I can see there'd be no way to represent such a tree diff with just an array of change objects like we do with other diffs, but if you instead return a tree structure then is that even *useful* to a caller? How would they work with or display it? If they still have to recursively descend through the tree to work with it, then have you actually saved them any work?

I'm open to being persuaded that this makes sense but I'd want a spec of what the return type will look like and a plausible use-case.
