### ISSUE TITLE
How to use jsdiff to get the similarity percentage between 2 string

### ISSUE THREAD

**Issue by dawoodaijaz97** [kpdecker/jsdiff#278]
Hello,
I am developing an application that detects the similarity between 2 documents. This diff library detects the changes can I somehow get the similarity percentage?

**Comment by ExplodingCabbage** [comment]
A possible approach would be to add up the `count`s of change objects for conserved/unchanged text (i.e. where `added` and `removed` are both falsey) and divide it by the sum of the `count`s of *all* change objects (including ones where `added` is `true` or `removed` is `true`). This will give you 0 in the case where there's no common content (i.e. the entire old text gets deleted and the entire new text gets inserted in its place), 1 in the case where the texts are identical, and a value between 0 and 1 otherwise. Whether the values between 0 and 1 will match a human intuition of the "similarity percentage" between two texts, though, I don't know.
