### ISSUE TITLE
[bug] Incorrectly lines comparing

### ISSUE THREAD

**Issue by kosaa** [kpdecker/jsdiff#282]
Text A:
```
a b CDE f
g


h L

j
```

Text B:
```
a b XYZ d
g

h Y

j
```

Diff objects list:
```
0: {count: 1, added: undefined, removed: true, value: "a b CDE f↵"}
1: {count: 1, added: true, removed: undefined, value: "a b XYZ d↵"}
2: {count: 2, value: "g↵↵"}
3: {count: 1, added: true, removed: undefined, value: "h Y↵"}
4: {count: 1, value: "↵"}
5: {count: 2, added: undefined, removed: true, value: "h L↵↵"}
6: {count: 1, value: "j"}
```

Wrong object:
```
3: {count: 1, added: true, removed: undefined, value: "h Y↵"}
```

Expected object:
```
3: {count: 1, added: true, removed: undefined, value: "↵h Y"}
```

In results one new line character between `h Y` and `j` is missing

Environment
- macOS 10.15.3
- Google Chrome v80.0.3987.149
- diff: v4.0.2
- compare mode: diffLines
- options: default

**Comment by g39088902** [comment]
I guess there is a logic mistake in jsdiff/src/diff/base.js

**Comment by ExplodingCabbage** [comment]
I can repro the results, but I don't see the bug.

```
> result = diff.diffLines(text1, text2)
[
  { count: 1, added: undefined, removed: true, value: 'a b CDE f\n' },
  { count: 1, added: true, removed: undefined, value: 'a b XYZ d\n' },
  { count: 2, value: 'g\n\n' },
  { count: 1, added: true, removed: undefined, value: 'h Y\n' },
  { count: 1, value: '\n' },
  { count: 2, added: undefined, removed: true, value: 'h L\n\n' },
  { count: 1, value: 'j' }
]
> result.filter(obj => !obj.added).map(obj=>obj.value).join('') == text1
true
> result.filter(obj => !obj.removed).map(obj=>obj.value).join('') == text2
true
```

> In results one new line character between h Y and j is missing

No there isn't. It's right there in your post:

```
4: {count: 1, value: "↵"}
```

It's just a slightly unintuitive diff because instead of simply deleting the extra blank line that appears *before* the `h L` in the first text and inserting the `h Y` where the `h L` was, the algo instead inserts the `h L` one line earlier and deletes a blank line that appears *after* the `h L`. This approach still gives a correct diff with the minimal number of edits, though, so it's not wrong.
