### ISSUE TITLE
Context option not working?

### ISSUE THREAD

**Issue by thercyl** [kpdecker/jsdiff#381]
Hi, I tried doing `Diff.createTwoFilesPatch('c.txt', 'd.txt', c, d, {newlineIsToken: true, ignoreWhitespace: true, context: Number.MAX_SAFE_INTEGER})` where `c.txt` and `d.txt` contain 10 lines in each file. There is only one line of difference between the two files but I want to show **all** remaining unchanged text as well. But right now, it will only return the first five lines (`@@ -1,5 +1,5 @@`) no matter what i set the `context` option to (eg I tried doing `context:50`). Is the context function working?

**Comment by ExplodingCabbage** [comment]
Hmm. Two problems here:

* `options` is *seventh* option to `createTwoFilesPatch`, not the fifth.
* `newlineIsToken: true` and `ignoreWhitespace: true` are basically incompatible with each other, especially when used with a patch-generation function, since the former breaks the newlines out into their own tokens, and the latter strips out leading and trailing whitespace from each token, so you end up basically deleting all the newlines and returning a diff where it's like they don't exist.

You want something like this:

```
Diff.createTwoFilesPatch('c.txt', 'd.txt', c, d, undefined, undefined, {context: Number.MAX_SAFE_INTEGER})
```
