### ISSUE TITLE
Add timeout?

### ISSUE THREAD

**Issue by hyrious** [kpdecker/jsdiff#398]
Can we add an option like [`diff_match_path.Diff_Timeout`](https://github.com/google/diff-match-patch/blob/62f2e689f498f9c92dbc588c58750addec9b1654/javascript/diff_match_patch_uncompressed.js#L34-L35) in [sync](https://github.com/google/diff-match-patch/blob/62f2e689f498f9c92dbc588c58750addec9b1654/javascript/diff_match_patch_uncompressed.js#L344-L347) mode? Since #396 may not be solved easily, this option can help reducing many issues about performance like #376

**Comment by quark-zju** [comment]
FWIW, `diff_match_path.Diff_Timeout` does not seem to actually work in its Javascript version. Whatever value it is set, the dmp diff algorithm takes the same time. And if the timeout is too small, the diff output is suboptimal (the computation for the more optimal diff is done but dropped due to the timeout logic). So in practice you always want to set it to a large value to avoid discarding the optimal diff output.

**Comment by ExplodingCabbage** [comment]
Not directly relevant to jsdiff, but for the record, I see different behaviour with `diff_match_patch` to what you describe, @quark-zju. I tried diffing two random million-line strings against each other with differing `Diff_Timeout` values and the `Diff_Timeout` clearly had an effect; when set to 1, execution finished after about 1 second, when set to 10, after about 10 seconds.
