### ISSUE TITLE
unexpected diffchars result

### ISSUE THREAD

**Issue by void285** [kpdecker/jsdiff#514]
Hi, this is unexpected:
```js
let old = 'abddefg';
let new = 'abcdefg';
let diff = Diff.diffChars(old, new);
console.log(diff);
```
expected:
![image](https://github.com/kpdecker/jsdiff/assets/612912/bc54222c-245b-42c8-99c7-a5bbbc4c4b95)

but got:
![image](https://github.com/kpdecker/jsdiff/assets/612912/452fb713-5bcb-43e3-ba5b-03b9f38ddda3)

Is there any option to achieve the expected result? Thanks.

**Comment by ExplodingCabbage** [comment]
No, there's no option that will achieve the result you want here; the result jsdiff gives is the one that the Myers diff algorithm, implemented as described in Myers's paper, gives. I'm not totally opposed to concrete proposals about options for tweaking this, but I'm not sure what such an option would look like (nor indeed what underlying rule you're envisaging that makes your "expected" output here be, well, expected).

**Comment by kerams** [comment]
> nor indeed what underlying rule you're envisaging that makes your "expected" output here be, well, expected

The Levenshtein distance between the two strings is 1, so a diff would ideally contain a single substitution (i.e. insertion and deletion at the same index).

**Comment by ExplodingCabbage** [comment]
@kerams aha - you're thinking in terms of substitutions! Okay, https://github.com/kpdecker/jsdiff/issues/475 is the issue that would give you what you want, then - but it'd be a drastic addition of an entirely new algorithm to the library. The Myers diff algorithm has no concept of substitutions - only of insertions and deletions - which is why it sees the two diffs in @void285's post as having equal edit distance.
