### ISSUE TITLE
support for more than 2 comparision ?

### ISSUE THREAD

**Issue by rajeevbarde** [kpdecker/jsdiff#563]
Read the doc but cannot find it . Just want to know if comparison of 5 input is possible and show difference ?  Example below

input 1 : It's a rainy day and temperature is 25C
input 2:  Its a sunny day and temp is 25C
input 3 : It a  hot day and temperature is 25C
input 4 : It's a cold  night, and temperature is -5C
input 5 : It's a rainy day and temperature is 18C

**Comment by ExplodingCabbage** [comment]
No, there's no support for this currently. (It's also not obvious to me what you'd even want the output to look like or what algorithm we'd use for this. I guess maybe something akin to [multiple sequence alignment](https://en.wikipedia.org/wiki/Multiple_sequence_alignment) in bioinformatics.)

I'm not sure I'd even want to accept a patch introducing this feature because I'm not sure it would have any overlap with the rest of the features library. In this way this idea is *unlike* [Levenshtein distance](https://github.com/kpdecker/jsdiff/issues/475); at least we can make Myers diffs and Levenshtein diffs use the same output format, just with Myers ones not featuring any substitutions, and so they'd be different algorithms that can be selected via a parameter within the same overall interface. But this kind of multiple alignment would require different input and output formats AND a new diffing algorithm, as far as I can see. I think at that point it ought to live in a different library.

**Comment by ExplodingCabbage** [comment]
(Sorry for typos, have just edited.)

**Comment by rajeevbarde** [comment]
thanks for explanation, I am also not sure how the output will look like.
