### ISSUE TITLE
insert some lines and modify next line makes conflict

### ISSUE THREAD

**Issue by legendhl** [kpdecker/jsdiff#568]
for example, data is:
```
const mine = `{"3":"00001","5":"abcdefg 1"}
{"3":"00005","5":"abcdefg 5!"}
`;
const base = `{"3":"00001","5":"abcdefg 1"}
{"3":"00005","5":"abcdefg 5"}
`;
const theirs = `{"3":"00001","5":"abcdefg 1"}
{"3":"00002","5":"abcdefg 2"}
{"3":"00003","5":"abcdefg 3"}
{"3":"00004","5":"abcdefg 4"}
{"3":"00005","5":"abcdefg 5"}
`;
```
using diff command in Mac, the result below is what we expected:
```
{"3":"00001","5":"abcdefg 1"}
{"3":"00002","5":"abcdefg 2"}
{"3":"00003","5":"abcdefg 3"}
{"3":"00004","5":"abcdefg 4"}
{"3":"00005","5":"abcdefg 5!"}
```
but using jsdiff library, there is a conflict, the code is:
```
const parsedDiff = merge(mine, theirs, base);
const merged = applyPatch(base, parsedDiff);
```
So is it my mistake in using it, or does jsdiff not support merging in this situation

**Comment by ExplodingCabbage** [comment]
I'll answer the explicit question first - you've made no mistake here. jsdiff doesn't support merging here.

This is an interesting case to think about. I'm curious - how are you applying / merging the patches from the command line that is happy to apply these? You say you're using `diff` but at least my Ubuntu version of `diff` only generates patches and doesn't (unless I've missed a feature!) apply them; did you mean to say you applied them using the `patch` command?

I do note that Git (... or at least the version of Git on my machine!) agrees with jsdiff that this is a merge conflict.

Treating it as a conflict seems reasonable to me, although I can imagine the rough outline of an alternative (better?) merge algorithm that would be able to merge these patches automatically. Let me try to outline two coherent ways of thinking about the problem - jsdiff's, and a sketch of an alternative way that better matches your intuition.

### Perspective 1 (how jsdiff sees things)

jsdiff has no concept of a line being "modified". (Indeed the unified diff format conventionally used for patches also has no concept of a line being "modified".) There are only insertions and deletions. In text `mine`, the line `{"3":"00005","5":"abcdefg 5"}` was deleted and the completely different line `{"3":"00005","5":"abcdefg 5!"}` was inserted. That there is only one character of difference between these two lines is entirely irrelevant.

In `theirs`, the line `{"3":"00005","5":"abcdefg 5"}` was *not* deleted, and several other lines were inserted before it.

This makes merging the patches automatically risky and forces any automatic merge to make some arbitrary choices:

1. Should the line `{"3":"00005","5":"abcdefg 5!"}` (inserted in `mine`) end up *before* or *after* the lines inserted in `theirs`? There is no reason to favour one order over the other.
2. Is it still valid to insert the stuff from `theirs` given that the line `{"3":"00005","5":"abcdefg 5"}` has been deleted? Since the inserted lines were adjacent to that line, there's a fairly high risk that they are coupled to it in some way and no longer make sense with it deleted.

Therefore the only safe thing to do is fail and complain of a conflict.

### Perspective 2 (how you are intuitively thinking about this)

The change made in `mine` is clearly a *modification* (namely inserting a single `!` character) to a line from `base`. We can tell this because the line is long and most characters on it are unchanged. The merge algorithm should recognise this and represent the change as a *line modification*, not as an insertion + deletion pair.

Once we have understood the change in this way, there is no longer any conflict. We understand that the line with the added `!` is in some sense the "same" line that the insertions from `theirs` are meant to go before, just modified. So we can happily do those insertions before it and all is well.

----

It'd be interesting to write a merge conflict resolver that is capable of "reasoning" in the second way outlined above. Perhaps there's one out there (no idea tbh - I don't know the space of current implementations very well). I *suspect* (but am not sure) that an algorithm capable of recognising "modifications" to lines like this would tend to do a better job of automatic merging without letting through any significant number of bad merges (though this is conjecture and certainly not trivial to confirm or disconfirm).

But jsdiff doesn't do it (and nor does Git, I think?). Two lines that differ from each other by one character are as different from jsdiff's perspective as two lines that have no common characters at all, and when diffs are viewed from that perspective, this is a clear merge conflict and gets treated as such.

**Comment by ExplodingCabbage** [comment]
Closing this as I don't *think* I'd want to make any changes to jsdiff based on this, but I am certainly still interested in reading further discussion and don't mean closure to deter that.

**Comment by legendhl** [comment]
> This is an interesting case to think about. I'm curious - how are you applying / merging the patches from the command line that is happy to apply these? You say you're using `diff` but at least my Ubuntu version of `diff` only generates patches and doesn't (unless I've missed a feature!) apply them; did you mean to say you applied them using the `patch` command?
Yes, I also used the patch command. The complete command is below:
```
diff base local > diff_local.patch
diff base remote > diff_remote.patch
patch base < diff_local.patch -o merged_file // it equals local as a matter of course
patch merged_file < diff_remote.patch -o final_merged_file
```
