### ISSUE TITLE
Html support. Help! :)

### ISSUE THREAD

**Issue by unkw** [kpdecker/jsdiff#71]
Need "diffWordsHtml". For example:
old: `<span><i>test</i> <b>javascript</b></span>`
new: `<span><i>test production</i> javascript</span>`

Let it work as diffWords but with html tags

**Comment by kpdecker** [comment]
@unkw I need more explanation. For the input above, what do you want it to return as the changes?

**Comment by unkw** [comment]
I expect the output as:
- "production" as insert
- "javascript" as modified (since changed the tag)

**Comment by kpdecker** [comment]
How are you trying to use this? Just saying "javascript" because the tag changed without providing any information about what the tag that changed was does not seem very useful.

**Comment by unkw** [comment]
We have rich text editor. User can change text in editor, can change font from Bold to Italic. And i need show diff what was deleted in the text, what was modified or inserted.

**Comment by unkw** [comment]
@kpdecker will it be possible to realize it?

**Comment by kpdecker** [comment]
This is a non-trivial thing to implement as it requires more knowledge of the structure of the document than the text focused diff algorithm implemented here allows for. I'm not certain that the algorithms here are good candidates for this as they are currently implemented. That's to say that this won't be implemented in the immediate term but leaving this open to revisit if I or any members of the community have time. I'm glad to accept pull requests that tackle this feature.

**Comment by unkw** [comment]
I agree, this is not a trivial task. Thank you for the feedback and this nice library  ;)

**Comment by mhuebner** [comment]
+1 for HTML support.

**Comment by samrm111** [comment]
:+1:

**Comment by pedro93** [comment]
+1 for feature.

Just leaving a note here, the HTML support requested appears to be in essence a tree based diff algorithm which is wildly different from a text-based diff. 

There is a relatively old project which does this for xml https://github.com/fdintino/xydiff, I have not searched a long time but perhaps there are newer or even better open-source solutions available.

Perhaps an investigation into it could lead to the feature. Not sure how it can incorporated though.

**Comment by VitaliyDemchuk** [comment]
are there any updates on this issue? can someone find a workaround?

**Comment by dauletisataev** [comment]
Any updates on this? @kpdecker

**Comment by ExplodingCabbage** [comment]
> the HTML support requested appears to be in essence a tree based diff algorithm which is wildly different from a text-based diff

Not just a different algorithm, then, but probably a wholly different way of representing the results?

I figure that:
1. if you want to diff HTML just as unstructured 1D plain text, then you can use diffWords etc
2. if you want some kind of tree diffing algorithm, then that's a totally different problem with basically zero overlap with any existing functionality in jsdiff, and for that reason, I wouldn't want to add it to jsdiff. Better if a totally different algorithm gets its own package and its own maintainer rather than them being part of the same library just because they both belong to the broad family of "diffing algorithms".

Given the above, I'm going to close this. (Argument with this is welcome if others disagree, though, especially from anyone who has a very clear idea of what the functionality they want to see would look like and why it makes sense for it to live in jsdiff.)
